name: Update README with GitLab Activity

on:
  # Schedule the workflow to run daily at midnight UTC
  schedule:
    - cron: "0 6 * * *" # Runs at 06:00 UTC every day

  # Trigger the workflow manually or on a push to the default branch
  push:
    branches:
      - main # Replace 'main' with your default branch if different
  workflow_dispatch: # Allows you to trigger the workflow manually from the GitHub Actions interface

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch GitLab activity
        run: |
          curl --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
          "https://lab.git.boom.marker/api/v4/users/24/events" > gitlab_activity.json

      - name: Update README
        run: |
          echo "## Latest GitLab Activity" > new_readme.md
          jq '.[] | "- \(.action_name) in [\(.project_id)](\(.target_url))"' gitlab_activity.json >> new_readme.md
          cat new_readme.md README.md > temp.md && mv temp.md README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update GitLab activity"
          git push
