name: Update README with GitLab Activity

on:
  schedule:
    - cron: "0 6 * * *" # Runs at 06:00 UTC every day
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch GitLab activity (with pagination)
        run: |
          echo "[]" > gitlab_activity.json
          page=1
          while true; do
            # Fetch a page of results
            response=$(curl -s --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
              "https://lab.git.boom.market/api/v4/users/24/events?page=$page&per_page=100")
            
            # Stop if no more results
            if [ "$(echo $response | jq '. | length')" -eq 0 ]; then
              break
            fi
            
            # Append results to the main JSON file
            jq -s '.[0] + .[1]' gitlab_activity.json <(echo "$response") > temp.json && mv temp.json gitlab_activity.json
            
            # Increment the page counter
            page=$((page + 1))
          done

      - name: Generate Contribution Summary by Month
        run: |
          echo "## ![GitLab Activity](https://img.shields.io/badge/GitLab-Activity-blue?logo=gitlab)" > new_readme.md

          # Filter contributions since January 2024 and group by month
          jq -r '[.[] | select(.created_at >= "2024-01-01T00:00:00Z") | .created_at[:7]] | group_by(.) | map({month: .[0], count: length}) | sort_by(.month) | .[] | "\(.month): \(.count) contributions"' gitlab_activity.json > contributions.txt

          # Calculate the maximum activity in any month for normalization
          max_count=$(awk -F': ' '{print $2}' contributions.txt | tr -d ' contributions' | sort -nr | head -1)
          max_squares=10 # Maximum number of squares per month

          # Generate a normalized graph
          echo "### Contribution Graph (Month by Month)" >> new_readme.md
          while read -r line; do
            month=$(echo $line | cut -d':' -f1)
            count=$(echo $line | cut -d':' -f2 | tr -d ' contributions')
            squares=$((count * max_squares / max_count)) # Normalize to a max of 10 squares
            printf "$month: " >> new_readme.md
            for i in $(seq 1 $squares); do printf "■" >> new_readme.md; done
            printf " ($count contributions)\n" >> new_readme.md # Add a newline here
          done < contributions.txt

          # Append to README
          cat new_readme.md README.md > temp.md && mv temp.md README.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update GitLab activity"
          git push
