name: Update README with GitLab Activity

on:
  schedule:
    - cron: "0 6 * * *" # Runs at 06:00 UTC every day
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch GitLab activity
        run: |
          curl --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
          "https://lab.git.boom.market/api/v4/users/24/events" > gitlab_activity.json

      - name: Generate Contribution Summary
        run: |
          echo "## ![GitLab Activity](https://img.shields.io/badge/GitLab-Activity-blue?logo=gitlab)" > new_readme.md

          # Count contributions per day
          jq -r '[.[] | .created_at[:10]] | group_by(.) | map({date: .[0], count: length}) | sort_by(.date) | .[] | "\(.date): \(.count) contributions"' gitlab_activity.json > contributions.txt

          # Generate a graph
          echo "### Contribution Graph" >> new_readme.md
          while read -r line; do
            date=$(echo $line | cut -d':' -f1)
            count=$(echo $line | cut -d':' -f2 | tr -d ' contributions')
            printf "$date: " >> new_readme.md
            for i in $(seq 1 $count); do printf "■" >> new_readme.md; done
            printf "\n" >> new_readme.md
          done < contributions.txt

          # Append to README
          cat new_readme.md README.md > temp.md && mv temp.md README.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update GitLab activity"
          git push
