name: Update README with GitLab Activity

on:
  # Schedule the workflow to run daily at XX UTC
  # schedule:
  #   - cron: "0 6 * * *" # Runs at 06:00 UTC every day

  # Trigger the workflow manually or on a push to the default branch
  push:
    branches:
      - main # Replace 'main' with your default branch if different
  workflow_dispatch: # Allows you to trigger the workflow manually from the GitHub Actions interface

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch GitLab activity (with pagination)
        run: |
          echo "[]" > gitlab_activity.json
          page=1
          while true; do
            # Fetch a page of results
            response=$(curl -s --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
              "https://lab.git.boom.market/api/v4/users/24/events?page=$page&per_page=100")
            
            # Stop if no more results
            if [ "$(echo $response | jq '. | length')" -eq 0 ]; then
              break
            fi
            
            # Append results to the main JSON file
            jq -s '.[0] + .[1]' gitlab_activity.json <(echo "$response") > temp.json && mv temp.json gitlab_activity.json
            
            # Increment the page counter
            page=$((page + 1))
          done

      - name: Generate Contribution Summary for 2024
        run: |
          echo "## ![GitLab Activity](https://img.shields.io/badge/GitLab-Activity-blue?logo=gitlab)" > new_readme.md
          echo "### Contribution Graph (Month by Month)" >> new_readme.md
          echo "" >> new_readme.md
          echo "| Month      | Contributions | Graph                               |" >> new_readme.md
          echo "|------------|---------------|-------------------------------------|" >> new_readme.md

          # Define month_map
          declare -A month_map=(
            ["01"]="Jan"
            ["02"]="Feb"
            ["03"]="Mar"
            ["04"]="Apr"
            ["05"]="May"
            ["06"]="Jun"
            ["07"]="Jul"
            ["08"]="Aug"
            ["09"]="Sep"
            ["10"]="Oct"
            ["11"]="Nov"
            ["12"]="Dec"
          )

          # Filter contributions for the year 2024 and group by month
          jq -r '[.[] | select(.created_at >= "2024-01-01T00:00:00Z" and .created_at < "2025-01-01T00:00:00Z") | .created_at[:7]] | group_by(.) | map({month: .[0], count: length}) | sort_by(.month) | .[] | "\(.month): \(.count) contributions"' gitlab_activity.json > contributions.txt

          # Calculate the maximum activity in any month for normalization
          max_count=$(awk -F': ' '{print $2}' contributions.txt | tr -d ' contributions' | sort -nr | head -1)
          max_squares=25 # Maximum number of squares per month

          # Generate a normalized table row with a logarithmic scale for square calculation
          while read -r line; do
            raw_month=$(echo $line | cut -d':' -f1)
            year=${raw_month:0:4}
            month_num=${raw_month:5:2}
            month_name=${month_map[$month_num]}
            formatted_month="$month_name $year"

            count=$(echo $line | cut -d':' -f2 | tr -d ' contributions')
            squares=$(awk -v c=$count -v max=$max_count -v m_sq=$max_squares 'BEGIN {print int(log(1 + c) / log(1 + max) * m_sq)}')
            graph=""
            for i in $(seq 1 $squares); do graph="${graph}■"; done
            printf "| %-10s | %-13s | %-35s |\n" "$formatted_month" "$count" "$graph" >> new_readme.md
          done < contributions.txt

          # Append to README
          cat new_readme.md README.md > temp.md && mv temp.md README.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update GitLab activity"
          git push
